/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CrowdfundingFactory {
  export type CampaignStruct = {
    campaignAddress: AddressLike;
    owner: AddressLike;
    name: string;
    creationTime: BigNumberish;
  };

  export type CampaignStructOutput = [
    campaignAddress: string,
    owner: string,
    name: string,
    creationTime: bigint
  ] & {
    campaignAddress: string;
    owner: string;
    name: string;
    creationTime: bigint;
  };
}

export interface CrowdfundingFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveCampaignWithdrawal"
      | "campaignLastWithdrawalApproval"
      | "campaignPaused"
      | "campaignUnderReview"
      | "campaigns"
      | "createCampaign"
      | "getAllCampaigns"
      | "getCampaignGovernance"
      | "getUserCampaigns"
      | "owner"
      | "paused"
      | "setCampaignPause"
      | "setCampaignUnderReview"
      | "togglePause"
      | "userCampaigns"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignPaused"
      | "CampaignUnderReview"
      | "CampaignWithdrawalApproved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveCampaignWithdrawal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignLastWithdrawalApproval",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignPaused",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignUnderReview",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCampaigns",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setCampaignPause",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCampaignUnderReview",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "togglePause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "userCampaigns",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveCampaignWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignLastWithdrawalApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignUnderReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCampaignUnderReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "togglePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCampaigns",
    data: BytesLike
  ): Result;
}

export namespace CampaignPausedEvent {
  export type InputTuple = [campaign: AddressLike, isPaused: boolean];
  export type OutputTuple = [campaign: string, isPaused: boolean];
  export interface OutputObject {
    campaign: string;
    isPaused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignUnderReviewEvent {
  export type InputTuple = [campaign: AddressLike, underReview: boolean];
  export type OutputTuple = [campaign: string, underReview: boolean];
  export interface OutputObject {
    campaign: string;
    underReview: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignWithdrawalApprovedEvent {
  export type InputTuple = [campaign: AddressLike, approvedAt: BigNumberish];
  export type OutputTuple = [campaign: string, approvedAt: bigint];
  export interface OutputObject {
    campaign: string;
    approvedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrowdfundingFactory extends BaseContract {
  connect(runner?: ContractRunner | null): CrowdfundingFactory;
  waitForDeployment(): Promise<this>;

  interface: CrowdfundingFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveCampaignWithdrawal: TypedContractMethod<
    [_campaign: AddressLike],
    [void],
    "nonpayable"
  >;

  campaignLastWithdrawalApproval: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  campaignPaused: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  campaignUnderReview: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        campaignAddress: string;
        owner: string;
        name: string;
        creationTime: bigint;
      }
    ],
    "view"
  >;

  createCampaign: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _goal: BigNumberish,
      _durationInDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getAllCampaigns: TypedContractMethod<
    [],
    [CrowdfundingFactory.CampaignStructOutput[]],
    "view"
  >;

  getCampaignGovernance: TypedContractMethod<
    [_campaign: AddressLike],
    [
      [boolean, boolean, bigint] & {
        isPaused: boolean;
        isUnderReview: boolean;
        lastWithdrawalApproval: bigint;
      }
    ],
    "view"
  >;

  getUserCampaigns: TypedContractMethod<
    [_user: AddressLike],
    [CrowdfundingFactory.CampaignStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  setCampaignPause: TypedContractMethod<
    [_campaign: AddressLike, _shouldPause: boolean],
    [void],
    "nonpayable"
  >;

  setCampaignUnderReview: TypedContractMethod<
    [_campaign: AddressLike, _underReview: boolean],
    [void],
    "nonpayable"
  >;

  togglePause: TypedContractMethod<[], [void], "nonpayable">;

  userCampaigns: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        campaignAddress: string;
        owner: string;
        name: string;
        creationTime: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveCampaignWithdrawal"
  ): TypedContractMethod<[_campaign: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "campaignLastWithdrawalApproval"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaignPaused"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "campaignUnderReview"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        campaignAddress: string;
        owner: string;
        name: string;
        creationTime: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _goal: BigNumberish,
      _durationInDays: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllCampaigns"
  ): TypedContractMethod<
    [],
    [CrowdfundingFactory.CampaignStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignGovernance"
  ): TypedContractMethod<
    [_campaign: AddressLike],
    [
      [boolean, boolean, bigint] & {
        isPaused: boolean;
        isUnderReview: boolean;
        lastWithdrawalApproval: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCampaigns"
  ): TypedContractMethod<
    [_user: AddressLike],
    [CrowdfundingFactory.CampaignStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "setCampaignPause"
  ): TypedContractMethod<
    [_campaign: AddressLike, _shouldPause: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCampaignUnderReview"
  ): TypedContractMethod<
    [_campaign: AddressLike, _underReview: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "togglePause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userCampaigns"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint] & {
        campaignAddress: string;
        owner: string;
        name: string;
        creationTime: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "CampaignPaused"
  ): TypedContractEvent<
    CampaignPausedEvent.InputTuple,
    CampaignPausedEvent.OutputTuple,
    CampaignPausedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignUnderReview"
  ): TypedContractEvent<
    CampaignUnderReviewEvent.InputTuple,
    CampaignUnderReviewEvent.OutputTuple,
    CampaignUnderReviewEvent.OutputObject
  >;
  getEvent(
    key: "CampaignWithdrawalApproved"
  ): TypedContractEvent<
    CampaignWithdrawalApprovedEvent.InputTuple,
    CampaignWithdrawalApprovedEvent.OutputTuple,
    CampaignWithdrawalApprovedEvent.OutputObject
  >;

  filters: {
    "CampaignPaused(address,bool)": TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;
    CampaignPaused: TypedContractEvent<
      CampaignPausedEvent.InputTuple,
      CampaignPausedEvent.OutputTuple,
      CampaignPausedEvent.OutputObject
    >;

    "CampaignUnderReview(address,bool)": TypedContractEvent<
      CampaignUnderReviewEvent.InputTuple,
      CampaignUnderReviewEvent.OutputTuple,
      CampaignUnderReviewEvent.OutputObject
    >;
    CampaignUnderReview: TypedContractEvent<
      CampaignUnderReviewEvent.InputTuple,
      CampaignUnderReviewEvent.OutputTuple,
      CampaignUnderReviewEvent.OutputObject
    >;

    "CampaignWithdrawalApproved(address,uint256)": TypedContractEvent<
      CampaignWithdrawalApprovedEvent.InputTuple,
      CampaignWithdrawalApprovedEvent.OutputTuple,
      CampaignWithdrawalApprovedEvent.OutputObject
    >;
    CampaignWithdrawalApproved: TypedContractEvent<
      CampaignWithdrawalApprovedEvent.InputTuple,
      CampaignWithdrawalApprovedEvent.OutputTuple,
      CampaignWithdrawalApprovedEvent.OutputObject
    >;
  };
}
