/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace Crowdfunding {
  export type TierStruct = {
    name: string;
    amount: BigNumberish;
    backers: BigNumberish;
  };

  export type TierStructOutput = [
    name: string,
    amount: bigint,
    backers: bigint
  ] & { name: string; amount: bigint; backers: bigint };
}

export interface CrowdfundingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "WITHDRAWAL_DELAY"
      | "addTier"
      | "backers"
      | "deadline"
      | "description"
      | "extendDeadline"
      | "factory"
      | "factoryApproveWithdrawal"
      | "fund"
      | "getCampaignStatus"
      | "getContractBalance"
      | "getTiers"
      | "goal"
      | "hasFundedTier"
      | "name"
      | "owner"
      | "paused"
      | "refund"
      | "removeTier"
      | "requestWithdrawal"
      | "setPauseFromFactory"
      | "setUnderReview"
      | "state"
      | "tiers"
      | "togglePause"
      | "underReview"
      | "withdraw"
      | "withdrawalApproved"
      | "withdrawalRequestTime"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FactoryPauseToggled"
      | "UnderReviewToggled"
      | "WithdrawalApproved"
      | "WithdrawalRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "WITHDRAWAL_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addTier",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "backers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "deadline", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "description",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "extendDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "factoryApproveWithdrawal",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "fund", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getCampaignStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getTiers", values?: undefined): string;
  encodeFunctionData(functionFragment: "goal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasFundedTier",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "refund", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPauseFromFactory",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUnderReview",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "state", values?: undefined): string;
  encodeFunctionData(functionFragment: "tiers", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "togglePause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "underReview",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawalApproved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalRequestTime",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "WITHDRAWAL_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addTier", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "backers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deadline", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "description",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "extendDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "factoryApproveWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTiers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "goal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasFundedTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "refund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "removeTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPauseFromFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUnderReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "state", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tiers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "togglePause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "underReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalRequestTime",
    data: BytesLike
  ): Result;
}

export namespace FactoryPauseToggledEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnderReviewToggledEvent {
  export type InputTuple = [underReview: boolean];
  export type OutputTuple = [underReview: boolean];
  export interface OutputObject {
    underReview: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalApprovedEvent {
  export type InputTuple = [approvedAt: BigNumberish];
  export type OutputTuple = [approvedAt: bigint];
  export interface OutputObject {
    approvedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalRequestedEvent {
  export type InputTuple = [requestedAt: BigNumberish];
  export type OutputTuple = [requestedAt: bigint];
  export interface OutputObject {
    requestedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Crowdfunding extends BaseContract {
  connect(runner?: ContractRunner | null): Crowdfunding;
  waitForDeployment(): Promise<this>;

  interface: CrowdfundingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  WITHDRAWAL_DELAY: TypedContractMethod<[], [bigint], "view">;

  addTier: TypedContractMethod<
    [_name: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  backers: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deadline: TypedContractMethod<[], [bigint], "view">;

  description: TypedContractMethod<[], [string], "view">;

  extendDeadline: TypedContractMethod<
    [_daysToAdd: BigNumberish],
    [void],
    "nonpayable"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  factoryApproveWithdrawal: TypedContractMethod<[], [void], "nonpayable">;

  fund: TypedContractMethod<[_tierIndex: BigNumberish], [void], "payable">;

  getCampaignStatus: TypedContractMethod<[], [bigint], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getTiers: TypedContractMethod<[], [Crowdfunding.TierStructOutput[]], "view">;

  goal: TypedContractMethod<[], [bigint], "view">;

  hasFundedTier: TypedContractMethod<
    [_backer: AddressLike, _tierIndex: BigNumberish],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  refund: TypedContractMethod<[], [void], "nonpayable">;

  removeTier: TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;

  requestWithdrawal: TypedContractMethod<[], [void], "nonpayable">;

  setPauseFromFactory: TypedContractMethod<
    [_paused: boolean],
    [void],
    "nonpayable"
  >;

  setUnderReview: TypedContractMethod<
    [_underReview: boolean],
    [void],
    "nonpayable"
  >;

  state: TypedContractMethod<[], [bigint], "view">;

  tiers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        name: string;
        amount: bigint;
        backers: bigint;
      }
    ],
    "view"
  >;

  togglePause: TypedContractMethod<[], [void], "nonpayable">;

  underReview: TypedContractMethod<[], [boolean], "view">;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  withdrawalApproved: TypedContractMethod<[], [boolean], "view">;

  withdrawalRequestTime: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "WITHDRAWAL_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addTier"
  ): TypedContractMethod<
    [_name: string, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "backers"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "description"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "extendDeadline"
  ): TypedContractMethod<[_daysToAdd: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "factoryApproveWithdrawal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<[_tierIndex: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getCampaignStatus"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTiers"
  ): TypedContractMethod<[], [Crowdfunding.TierStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "goal"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasFundedTier"
  ): TypedContractMethod<
    [_backer: AddressLike, _tierIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "refund"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeTier"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestWithdrawal"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPauseFromFactory"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUnderReview"
  ): TypedContractMethod<[_underReview: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "state"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tiers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint] & {
        name: string;
        amount: bigint;
        backers: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "togglePause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "underReview"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawalApproved"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawalRequestTime"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "FactoryPauseToggled"
  ): TypedContractEvent<
    FactoryPauseToggledEvent.InputTuple,
    FactoryPauseToggledEvent.OutputTuple,
    FactoryPauseToggledEvent.OutputObject
  >;
  getEvent(
    key: "UnderReviewToggled"
  ): TypedContractEvent<
    UnderReviewToggledEvent.InputTuple,
    UnderReviewToggledEvent.OutputTuple,
    UnderReviewToggledEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalApproved"
  ): TypedContractEvent<
    WithdrawalApprovedEvent.InputTuple,
    WithdrawalApprovedEvent.OutputTuple,
    WithdrawalApprovedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalRequested"
  ): TypedContractEvent<
    WithdrawalRequestedEvent.InputTuple,
    WithdrawalRequestedEvent.OutputTuple,
    WithdrawalRequestedEvent.OutputObject
  >;

  filters: {
    "FactoryPauseToggled(bool)": TypedContractEvent<
      FactoryPauseToggledEvent.InputTuple,
      FactoryPauseToggledEvent.OutputTuple,
      FactoryPauseToggledEvent.OutputObject
    >;
    FactoryPauseToggled: TypedContractEvent<
      FactoryPauseToggledEvent.InputTuple,
      FactoryPauseToggledEvent.OutputTuple,
      FactoryPauseToggledEvent.OutputObject
    >;

    "UnderReviewToggled(bool)": TypedContractEvent<
      UnderReviewToggledEvent.InputTuple,
      UnderReviewToggledEvent.OutputTuple,
      UnderReviewToggledEvent.OutputObject
    >;
    UnderReviewToggled: TypedContractEvent<
      UnderReviewToggledEvent.InputTuple,
      UnderReviewToggledEvent.OutputTuple,
      UnderReviewToggledEvent.OutputObject
    >;

    "WithdrawalApproved(uint256)": TypedContractEvent<
      WithdrawalApprovedEvent.InputTuple,
      WithdrawalApprovedEvent.OutputTuple,
      WithdrawalApprovedEvent.OutputObject
    >;
    WithdrawalApproved: TypedContractEvent<
      WithdrawalApprovedEvent.InputTuple,
      WithdrawalApprovedEvent.OutputTuple,
      WithdrawalApprovedEvent.OutputObject
    >;

    "WithdrawalRequested(uint256)": TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
    WithdrawalRequested: TypedContractEvent<
      WithdrawalRequestedEvent.InputTuple,
      WithdrawalRequestedEvent.OutputTuple,
      WithdrawalRequestedEvent.OutputObject
    >;
  };
}
